### ISSUE TITLE
Downloading data from aws

### ISSUE THREAD

**Issue by arielmadr** [czbiohub/tabula-sapiens#33]
Hi, 

I was wondering if it's possible to download the raw data from amazon aws. Currently, when I'm trying to download a file through the webpage but I'm getting this message: 
![Screenshot from 2021-12-19 17-11-20](https://user-images.githubusercontent.com/40617646/146694356-6cce3ccc-65cf-4f70-a3db-f495eb0dbe8b.png)

Any help would be greatly appreciated. 

Best,

Ariel

**Comment by aopisco** [comment]
@arielmadr it is possible but we do require you to complete a data sharing agreement for ethical reasons. Can you please [email me](mailto:angela.pisco@czbiohub.org) and I'll get that processed for you? Thanks!
