### ISSUE TITLE
Reproducing UMAP from bioRxiv paper 10.1101/2021.07.19.452956v2

### ISSUE THREAD

**Issue by Rubbert** [czbiohub/tabula-sapiens#34]
Thank you for the wonderful resource! I plan to use it to map other datasets onto and to assign cell types.

In getting more familiar with the data, I wanted to reproduce Figure S2A of the bioRxiv paper 10.1101/2021.07.19.452956v2 . I can basically do this by following "Fig1_dataset_overview.ipynb" in this repo. However, this already has the trained result and I would like to start from the raw data and train the model myself instead on a subset of the data. I wasn't able to find the code or a description that shows how the count data was processed exactly. In the bioRxiv paper it mentions "For complete methods, see supplementary materials ([12](https://www.biorxiv.org/content/10.1101/2021.07.19.452956v2.full#ref-12)).", however, this links to the website http://tabula-sapiens-portal.ds.czbiohub.org/, and I wasn't able to find the methods there.

Is the code for that processing available (I might have missed it). If not, would it be possible to share the code that was used to get from the "raw" count data to the UMAP? Potentially there might be similar issues with reproducing other figures, but I did not check. Apologies if this is already there and I missed it.

Thanks in advance

**Comment by aopisco** [comment]
Hi @Rubbert did you check this notebook https://github.com/czbiohub/tabula-sapiens/blob/master/Fig1/Train_scVI.ipynb?
