### ISSUE TITLE
Batch Corrected Counts

### ISSUE THREAD

**Issue by BradBalderson** [czbiohub/tabula-sapiens#36]
Dear authors,

Thankyou for such fabulous work!

I'm using the Tabula Sapiens dataset in a project and need to use the batch/tech corrected count data. 

From the methods I guess there should be 3 different count matrices:

1. Raw counts
2. decontX counts
3. scVI batch/sample corrected counts

In the full .h5ad downloaded here: https://figshare.com/articles/dataset/Tabula_Sapiens_release_1_0/14267219/4?file=34702114

I can see 1 & 2 in data.layers, but not 3. It appears this is present in normalised/log1p form in data.X; however I need the batch corrected counts to continue. 

I can see the code here:
https://github.com/czbiohub/tabula-sapiens/blob/master/Fig1/Train_scVI.ipynb

This code would suggest 3 does not exist, but instead 2 is log1p & total count normalised. However if I perform the following with the .h5ad downloaded above, data.X and the renormalised data.layers['decontX'] don't match. 

**Just wondering if there is an additional step I am missing that includes some kind of scvi batch normalisation of the decontX counts?** 

Please see what I've tried below:
`
!wget https://figshare.com/ndownloader/files/34702114
!mv 34702114 TabulaSapiens.h5ad.zip
!unzip TabulaSapiens.h5ad.zip
!rm TabulaSapiens.h5ad.zip

data = sc.read_h5ad(data_dir+'TabulaSapiens.h5ad')

# Getting log1p normalised data...
orig = data[0:1000, data.var['highly_variable'].values].to_df().values

data.layers['log1p'] = data.X ### Cacheing....

# Try to reproduce this...
data.X = data.layers['decontXcounts'].copy()
sc.pp.normalize_total(data, target_sum=1e4)
sc.pp.log1p(data)
sc.pp.scale(data, max_value=10, zero_center=False)

orig_test = data[0:1000, data.var['highly_variable'].values].to_df().values

### Compare reproduction with original...
plt.scatter(orig_test.ravel(), orig.ravel()) #### Almost the same... not sure what could be different, no random steps here...
![image](https://user-images.githubusercontent.com/24308582/193480483-09105f0f-187f-421d-86a2-1b4eb4fb52ce.png)
`

Thankyou very much!

**Comment by aopisco** [comment]
Hi @BradBalderson, we did not computed the batch corrected counts. If you need those for your project, I suggest you re-run scvi from the decontx counts.
